
SELECT ID, CLIENT_ID, START_DATE, FINISH_DATE, DATEDIFF('DAY', CAST(FINISH_DATE AS DATE), CAST(START_DATE AS DATE)) / -30 AS duration_months
FROM project
WHERE DATEDIFF('DAY', CAST(FINISH_DATE AS DATE), CAST(START_DATE AS DATE)) = (
    SELECT MAX(DATEDIFF('DAY', CAST(FINISH_DATE AS DATE), CAST(START_DATE AS DATE)))
    FROM project
    WHERE FINISH_DATE IS NOT NULL AND START_DATE IS NOT NULL
)
  AND FINISH_DATE IS NOT NULL AND START_DATE IS NOT NULL;